name: "PR Checkout action"
description: "Checks out PR with hub cli"
runs:
  using: "composite"
  steps:
    - name: Checkout PR
      shell: bash
      run: |
        PR_URL="${{ github.event.issue.pull_request.url }}"
        PR_NUM=${PR_URL##*/}
        echo "Checking out from PR #$PR_NUM based on URL: $PR_URL"
        gh pr checkout $PR_NUM
    - name: Set slug
      shell: bash
      run: |
        run: echo "CI_HEAD_REF_SLUG=$(git branch --show-current | iconv -t ascii | sed -r s/[^a-zA-Z0-9]+/-/g | sed -r s/^-+\|-+$//g | tr A-Z a-z)" >> $GITHUB_ENV
        echo $CI_HEAD_REF_SLUG
